name: Build Client

on:
  push:
    branches:
      - 'nwjs-0.55.0-ffmpeg'

jobs:
  build-win32:
    strategy:
      matrix:
        targetplatform: [x86]

    runs-on: windows-2016

    env:
      GOPATH: 'C:\go'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: '16.4.2'
          architecture: 'x86'
          cache: 'yarn'
      - run: node --version
      - run: yarn --version

      - uses: actions/setup-go@v2
        with:
          go-version: '1.10.8'
      - run: go version

      # Enable VS2015 toolset
      - run: 'call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
        shell: cmd
      - run: gcc -v

      - run: echo %PATH%
        shell: cmd

      - run: yarn install --ignore-engines
      - run: yarn run client-build-win
