name: Build Client

on:
  push:
    branches:
      - 'nwjs-0.55.0-ffmpeg'

jobs:
  build-win32:
    strategy:
      matrix:
        targetplatform: [x86]

    runs-on: windows-2016

    env:
      GOPATH: 'C:\go'
      GJ_PUSH_TOKEN: ${{ secrets.GJ_PUSH_TOKEN }}
      GJ_CERT_PASS: ${{ secrets.GJ_CERT_PASS }}

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install code signing cert
        run: |
          Set-Content ${{ env.GITHUB_WORKSPACE }}\gulp\tasks\client\certs\cert.pfx.b64 ${{ secrets.GJ_CERT }}
          CertUtil -Decode ${{ env.GITHUB_WORKSPACE }}\gulp\tasks\client\certs\cert.pfx.b64 ${{ env.GITHUB_WORKSPACE }}\gulp\tasks\client\certs\cert.pfx

      - uses: actions/setup-node@v2
        with:
          node-version: '16.4.2'
          architecture: 'x86'
          cache: 'yarn'
      - run: node --version
      - run: yarn --version

      - uses: actions/setup-go@v2
        with:
          go-version: '1.10.8'
      - run: go version

      # Enable VS2015 toolset
      - run: 'call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
        shell: cmd
      - run: gcc -v

      - run: echo %PATH%
        shell: cmd

      - run: yarn install --ignore-engines
      - run: yarn run client-build-win

      - uses: actions/upload-artifact@v2
        with:
          name: win32
          path: build\prod-client-build\GameJoltClientSetup.exe

      - uses: actions/upload-artifact@v2
        with:
          name: win32-package
          path: build\prod-client-build\win32-package.tar.gz
